import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "HexVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className={`font-mono antialiased`}>{children}</body>
    </html>
  );
}
