import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "HexVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`bg-background font-mono antialiased selection:bg-[hsl(320,65%,52%,20%)]`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
